import '../style/style.js'
import '../img/logo.png'
import '../img/background.jpg'
import '../img/giphy.gif'
import '../svg/Home.svg'
import '../svg/Gear.svg'
import '../svg/Notes.svg'
import '../svg/Profile.svg'
import '../svg/statistic.svg'
import '../svg/user.svg'
import '../svg/Vector 59.svg'
import "./AuthForm.js"